application: meteread-hrd
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /stylesheets
  static_dir: static/stylesheets
  
- url: /images
  static_dir: static/images

- url: /cron/.*
  script: mread.app
  login: admin

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /.*
  script: mread.app

builtins:
- remote_api: on

libraries:
- name: jinja2
  version: "2.6"
