application: meteread
version: 1
runtime: python
api_version: 1

handlers:
- url: /stylesheets
  static_dir: static/stylesheets
  
- url: /images
  static_dir: static/images

- url: /cron/.*
  script: cron.py
  login: admin

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /.*
  script: mread.py

builtins:
- remote_api: on
- datastore_admin: on
- appstats: on